version: "3"
services:
  postgres:
    image: postgres
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/db/data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
    volumes:
      - ./backend:/usr/src/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    command: yarn dev --port 5000 --host 0.0.0.0
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5000:5000
