import { RewardsEntity } from './rewards.entity';

export const rewards: RewardsEntity[] = [
  {
    id: 1,
    rewardId: 'play_1_hour',
    title: 'Играть без остановки 1 час',
    type: 'TIME',
    condition: '1 час в игре',
    points: 3600, // В секундах
    lootboxPoints: 50,
  },
  {
    id: 2,
    rewardId: 'collect_200_points',
    title: 'Накопить 200 очков в игре',
    type: 'POINTS',
    condition: '200 очков',
    boost: 'Ускорение очков в 2 раза на 3 часа',
  },
  {
    id: 3,
    rewardId: 'login_3_days',
    title: 'Войти в игру каждый день на протяжении 3 дней',
    type: 'ACTIVITY',
    condition: '3 дня подряд',
    liquidityPools: 3,
  },
  {
    id: 4,
    rewardId: 'collect_700_points_5_days',
    title: 'Набрать 700 очков за первые 5 дней игры',
    type: 'CHALLENGE',
    condition: '700 очков за 5 дней',
    lootboxPoints: 75,
  },
  {
    id: 5,
    rewardId: 'catch_100_green_candles',
    title: 'Поймать 100 зеленых свечей',
    type: 'ITEMS',
    condition: '100 зелёных свечей',
    liquidityPools: 3,
  },
  {
    id: 6,
    rewardId: 'level_up_3_days',
    title: 'Увеличить уровень каждый день на протяжении 3 дней',
    type: 'CHALLENGE',
    condition: '3 дня повышения уровня',
    lootboxPoints: 100,
  },
  {
    id: 7,
    rewardId: 'login_7_days',
    title: 'Войти в игру каждый день на протяжении 7 дней',
    type: 'ACTIVITY',
    condition: '7 дней подряд',
    boost: 'Ускорение восстановления ликвидности на 20% на 2 дня',
  },
  {
    id: 8,
    rewardId: 'collect_1000_points',
    title: 'Накопить 1000 очков',
    type: 'POINTS',
    condition: '1000 очков',
    lootboxPoints: 150,
  },
  {
    id: 9,
    rewardId: 'catch_200_green_candles',
    title: 'Поймать 200 зеленых свечей',
    type: 'ITEMS',
    condition: '200 зелёных свечей',
    liquidityPools: 3,
  },
  {
    id: 10,
    rewardId: 'level_5_in_10_days',
    title: 'Достичь 5 уровня за 10 дней',
    type: 'CHALLENGE',
    condition: '5 уровень за 10 дней',
    boost: 'Ускорение очков в 2 раза на 5 часов',
  },
  {
    id: 11,
    rewardId: 'login_14_days',
    title: 'Войти в игру каждый день на протяжении 14 дней',
    type: 'ACTIVITY',
    condition: '14 дней подряд',
    liquidityPools: 5,
  },
  {
    id: 12,
    rewardId: 'collect_2000_points',
    title: 'Накопить 2000 очков',
    type: 'POINTS',
    condition: '2000 очков',
    lootboxPoints: 200,
  },
  {
    id: 13,
    rewardId: 'catch_500_green_candles',
    title: 'Поймать 500 зеленых свечей',
    type: 'ITEMS',
    condition: '500 зелёных свечей',
    lootboxPoints: 250,
  },
  {
    id: 14,
    rewardId: 'reach_level_8',
    title: 'Достичь 8 уровня',
    type: 'LEVEL',
    condition: '8 уровень',
    liquidityPools: 5,
  },
  {
    id: 15,
    rewardId: 'login_21_days',
    title: 'Войти в игру каждый день на протяжении 21 дня',
    type: 'ACTIVITY',
    condition: '21 день подряд',
    boost: 'Ускорение ликвидности на 30% на 5 дней',
  },
  {
    id: 16,
    rewardId: 'collect_3000_points',
    title: 'Накопить 3000 очков',
    type: 'POINTS',
    condition: '3000 очков',
    lootboxPoints: 300,
  },
  {
    id: 17,
    rewardId: 'catch_1000_green_candles',
    title: 'Поймать 1000 зеленых свечей',
    type: 'ITEMS',
    condition: '1000 зелёных свечей',
    liquidityPools: 10,
  },
  {
    id: 18,
    rewardId: 'level_10_in_30_days',
    title: 'Достичь 10 уровня за 30 дней',
    type: 'CHALLENGE',
    condition: '10 уровень за 30 дней',
    boost: 'Ускорение очков в 2 раза на 10 часов',
  },
  {
    id: 19,
    rewardId: 'collect_5000_points',
    title: 'Накопить 5000 очков',
    type: 'POINTS',
    condition: '5000 очков',
    lootboxPoints: 500,
  },
  {
    id: 20,
    rewardId: 'login_30_days',
    title: 'Войти в игру каждый день на протяжении 30 дней',
    type: 'ACTIVITY',
    condition: '30 дней подряд',
    boost: 'Ускорение ликвидности на 60% на 5 дней',
  },
  {
    id: 21,
    rewardId: 'catch_2000_green_candles',
    title: 'Поймать 2000 зеленых свечей',
    type: 'ITEMS',
    condition: '2000 зелёных свечей',
    liquidityPools: 10,
  },
  {
    id: 22,
    rewardId: 'reach_level_20',
    title: 'Достичь 20 уровня',
    type: 'LEVEL',
    condition: '20 уровень',
    boost: 'Эксклюзивный лутбокс с неограниченной ликвидностью на 3 дня',
  },
];
