import { RewardsEntity } from './rewards.entity';
import { BoostType } from '../rewards/dto/reward-progress.dto';

const hour = 60;
const day = 1440;

export const rewards: RewardsEntity[] = [
  {
    id: 1,
    rewardId: 'play_1_hour',
    title: 'Play for 1 hour without stopping',
    type: 'TIME',
    condition: 3600,
    lootboxPoints: 50,
    description: 'Lootbox with 50 points.',
  },
  {
    id: 2,
    rewardId: 'collect_200_points',
    title: 'Accumulate 200 points in the game',
    type: 'POINTS',
    condition: 200,
    boost: {
      type: BoostType.POINTS,
      description: 'Double points accumulation speed for 3 hours',
      multiplier: 2,
      duration: hour * 3,
      isPercentage: false,
    },
    description: 'Double points accumulation speed for 3 hours.',
  },
  {
    id: 3,
    rewardId: 'login_3_days',
    title: 'Log in to the game every day for 3 consecutive days',
    type: 'ACTIVITY',
    condition: 3,
    liquidityPools: 3,
    description: '+3 liquidity pools.',
  },
  {
    id: 4,
    rewardId: 'collect_700_points_5_days',
    title: 'Accumulate 700 points within the first 5 days of playing',
    type: 'CHALLENGE',
    condition: 700,
    lootboxPoints: 75,
    description: 'Lootbox with 75 points.',
  },
  {
    id: 5,
    rewardId: 'catch_100_green_candles',
    title: 'Catch 100 green candles',
    type: 'ITEMS',
    condition: 100,
    liquidityPools: 3,
    description: '+3 liquidity pools.',
  },
  {
    id: 6,
    rewardId: 'level_up_3_days',
    title: 'Level up every day for 3 consecutive days',
    type: 'CHALLENGE',
    condition: 3,
    lootboxPoints: 100,
    description: 'Lootbox with 100 points.',
  },
  {
    id: 7,
    rewardId: 'login_7_days',
    title: 'Log in to the game every day for 7 consecutive days',
    type: 'ACTIVITY',
    condition: 7,
    boost: {
      type: BoostType.LIQUIDITY,
      description: 'Liquidity recovery boost by 20% for 2 days',
      multiplier: 1.2,
      duration: day * 2,
      isPercentage: true,
    },
    description: 'Liquidity recovery boost by 20% for 2 days.',
  },
  {
    id: 8,
    rewardId: 'collect_1000_points',
    title: 'Accumulate 1000 points',
    type: 'POINTS',
    condition: 1000,
    lootboxPoints: 150,
    description: 'Lootbox with 150 points.',
  },
  {
    id: 9,
    rewardId: 'catch_200_green_candles',
    title: 'Catch 200 green candles',
    type: 'ITEMS',
    condition: 200,
    liquidityPools: 3,
    description: '+3 liquidity pools.',
  },
  {
    id: 10,
    rewardId: 'level_5_in_10_days',
    title: 'Reach level 5 within 10 days',
    type: 'CHALLENGE',
    condition: 5,
    boost: {
      type: BoostType.POINTS,
      description: 'Double points accumulation speed for 5 hours',
      multiplier: 2,
      duration: hour * 5,
      isPercentage: false,
    },
    description: 'Double points accumulation speed for 5 hours.',
  },
  {
    id: 11,
    rewardId: 'login_14_days',
    title: 'Log in to the game every day for 14 consecutive days',
    type: 'ACTIVITY',
    condition: 14,
    liquidityPools: 5,
    description: '+5 liquidity pools.',
  },
  {
    id: 12,
    rewardId: 'collect_2000_points',
    title: 'Accumulate 2000 points',
    type: 'POINTS',
    condition: 2000,
    lootboxPoints: 200,
    description: 'Lootbox with 200 points.',
  },
  {
    id: 13,
    rewardId: 'catch_500_green_candles',
    title: 'Catch 500 green candles',
    type: 'ITEMS',
    condition: 500,
    lootboxPoints: 250,
    description: 'Lootbox with 250 points.',
  },
  {
    id: 14,
    rewardId: 'reach_level_8',
    title: 'Reach level 8',
    type: 'LEVEL',
    condition: 8,
    liquidityPools: 5,
    description: '+5 liquidity pools.',
  },
  {
    id: 15,
    rewardId: 'login_21_days',
    title: 'Log in to the game every day for 21 consecutive days',
    type: 'ACTIVITY',
    condition: 21,
    boost: {
      type: BoostType.LIQUIDITY,
      description: 'Liquidity recovery boost by 30% for 5 days',
      multiplier: 1.3,
      duration: day * 5,
      isPercentage: true,
    },
    description: 'Liquidity recovery boost by 30% for 5 days.',
  },
  {
    id: 16,
    rewardId: 'collect_3000_points',
    title: 'Accumulate 3000 points',
    type: 'POINTS',
    condition: 3000,
    lootboxPoints: 300,
    description: 'Lootbox with 300 points.',
  },
  {
    id: 17,
    rewardId: 'catch_1000_green_candles',
    title: 'Catch 1000 green candles',
    type: 'ITEMS',
    condition: 1000,
    liquidityPools: 10,
    description: '+10 liquidity pools.',
  },
  {
    id: 18,
    rewardId: 'level_10_in_30_days',
    title: 'Reach level 10 within 30 days',
    type: 'CHALLENGE',
    condition: 10,
    boost: {
      type: BoostType.POINTS,
      description: 'Double points accumulation speed for 10 hours',
      multiplier: 2,
      duration: hour * 10,
      isPercentage: true,
    },
    description: 'Double points accumulation speed for 10 hours.',
  },
  {
    id: 19,
    rewardId: 'collect_5000_points',
    title: 'Accumulate 5000 points',
    type: 'POINTS',
    condition: 5000,
    lootboxPoints: 500,
    description: 'Lootbox with 500 points.',
  },
  {
    id: 20,
    rewardId: 'login_30_days',
    title: 'Log in to the game every day for 30 consecutive days',
    type: 'ACTIVITY',
    condition: 30,
    boost: {
      type: BoostType.LIQUIDITY,
      description: 'Liquidity recovery boost by 60% for 5 days',
      multiplier: 1.6,
      duration: day * 5,
      isPercentage: true,
    },
    description: 'Liquidity recovery boost by 60% for 5 days.',
  },
  {
    id: 21,
    rewardId: 'catch_2000_green_candles',
    title: 'Catch 2000 green candles',
    type: 'ITEMS',
    condition: 2000,
    liquidityPools: 10,
    description: '+10 liquidity pools.',
  },
  {
    id: 22,
    rewardId: 'reach_level_20',
    title: 'Reach level 20',
    type: 'LEVEL',
    condition: 20,
    boost: {
      type: BoostType.LIQUIDITY,
      description: 'Exclusive lootbox with unlimited liquidity for 3 days',
      multiplier: 100,
      duration: day * 3,
      isPercentage: true,
    },
    description: 'Exclusive lootbox with unlimited liquidity for 3 days.',
  },
];
