services:
  postgres:
    image: postgres
    restart: always
    env_file:
      - ../backend/.env
    ports:
      - "5432:5432"
    networks:
      - web
    volumes:
      - ../backend/db/data:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - ../backend/.env
    depends_on:
      - postgres
    networks:
      - web
    volumes:
      - ../backend:/usr/src/app

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    networks:
      - web
    command: yarn dev --port 5000 --host 0.0.0.0
    volumes:
      - ../frontend:/usr/src/app
    ports:
      - "5000:5000"

  nginx:
    build: nginx
    depends_on:
      - frontend
      - backend
      - postgres
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - web
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"


networks:
  web:
